In [1]:
import webotsgym as wg

from webotsgym.config import WebotConfig
from webotsgym.environment import WebotsEnv, WebotsGrid
from webotsgym.evaluate import Evaluate, EvaluateMats, EvaluatePJ0
from webotsgym.action import DiscreteAction, ContinuousAction
from webotsgym.observation import Observation

import numpy as np

import gym
import stable_baselines
from stable_baselines import A2C, ACER, ACKTR, DQN, DDPG, SAC, PPO1, PPO2, TD3, TRPO
from stable_baselines.common.env_checker import check_env
from stable_baselines.common.policies import MlpPolicy

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



In [2]:
config = WebotConfig()
config.fast_simulation = False
config.reset_env_after = 20000
config.num_obstacles = 0
config.world_size = 8
config.world_scaling = 0.5
#action_class = ContinuousAction(direction_type="steering", relative=False)
env = WebotsGrid(train=True, 
                 config=config)

/home/pj/anaconda3/envs/spinningup/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


Accepting on Port:  10201
sending: env
TARGET	: [2.25 2.75]


In [3]:
# load model from fakeEnv
model_name = 'gps_only'
model = PPO1.load("models/keep/{}".format(model_name))

Loading a model without an environment, this model cannot be trained until it has a valid environment.




Instructions for updating:
Use keras.layers.flatten instead.
Instructions for updating:
Please use `layer.__call__` method instead.










Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [4]:
for i in range(10):
    obs = env.reset()
    for _ in range(20):
        print(obs)
        action, _states = model.predict(obs)
        obs, rewards, done, info = env.step(action)

        if env.get_target_distance() < 0.1:
            print(_)
            break

sending: env
[6. 6. 4. 2.]
GPS vorher:	 [2.76 2.73]
GO: LEFT
GPS nacher:	 [2.75 2.26]
[6. 5. 4. 2.]
GPS vorher:	 [2.75 2.26]
GO: UP
GPS nacher:	 [2.26 2.25]
[5. 5. 4. 2.]
GPS vorher:	 [2.26 2.25]
GO: UP
GPS nacher:	 [1.76 2.25]
[4. 5. 4. 2.]
GPS vorher:	 [1.76 2.25]
GO: LEFT
GPS nacher:	 [1.75 1.76]
[4. 4. 4. 2.]
GPS vorher:	 [1.75 1.76]
GO: LEFT
GPS nacher:	 [1.75 1.26]
[4. 3. 4. 2.]
GPS vorher:	 [1.75 1.26]
GO: LEFT
GPS nacher:	 [1.75 0.76]
5
sending: env
[6. 2. 1. 8.]
GPS vorher:	 [2.74 0.77]
GO: RIGHT
GPS nacher:	 [2.75 1.24]
[6. 3. 1. 8.]
GPS vorher:	 [2.75 1.24]
GO: RIGHT
GPS nacher:	 [2.75 1.74]
[6. 4. 1. 8.]
GPS vorher:	 [2.75 1.74]
GO: RIGHT
GPS nacher:	 [2.75 2.24]
[6. 5. 1. 8.]
GPS vorher:	 [2.75 2.24]
GO: UP
GPS nacher:	 [2.26 2.25]
[5. 5. 1. 8.]
GPS vorher:	 [2.26 2.25]
GO: RIGHT
GPS nacher:	 [2.25 2.74]
[5. 6. 1. 8.]
GPS vorher:	 [2.25 2.74]
GO: UP
GPS nacher:	 [1.76 2.75]
[4. 6. 1. 8.]
GPS vorher:	 [1.76 2.75]
GO: UP
GPS nacher:	 [1.26 2.75]
[3. 6. 1. 8.]
GPS vorher:	 [1