In [3]:
import gym
import numpy as np

In [4]:
env = gym.make('FrozenLake-v0')

In [5]:
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [7]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.591


In [9]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[2.83349320e-01 4.54791964e-03 4.20556458e-03 4.82605528e-03]
 [7.40985407e-04 1.84577375e-03 8.19891195e-04 2.65679915e-01]
 [5.61476469e-03 4.34986333e-03 3.78611075e-03 7.83012594e-02]
 [1.08699550e-03 1.75657193e-04 8.52246367e-05 5.37387275e-02]
 [2.89860621e-01 1.60952413e-04 1.00632261e-03 3.93302771e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.30448952e-05 4.22651724e-05 5.21061599e-02 2.03264218e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.32835573e-04 3.05148455e-04 2.10440570e-04 4.61420599e-01]
 [1.55246904e-03 6.47982125e-01 3.22084997e-04 1.04687219e-03]
 [7.20363434e-01 0.00000000e+00 2.97444958e-03 1.36532462e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.33898287e-04 9.08362474e-04 8.61682184e-01 6.37450993e-04]
 [0.00000000e+00 9.89202272e-01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.